from django.urls import path
from .views import all, stat, get_room, commande, reserved, get_commande_reserved, filter_commande, room_unavailable, get_commande, get_all_commande, free_room, simulate_commande, confirmeCommande, get_commande_by_id, imageall, room_available, delete_image, search_room, image_room, createimage, create, update_by_admin, delete_by_admin, recover_by_admin, upload

urlpatterns = [
    path('all', all, name='all'),
    path('stat', stat, name='stat'),
    path('commande/create', commande, name='commande'),
    path('commande/reserved', reserved, name='reserved'),
    path('commande/confirme/<int:idCommande>', confirmeCommande, name='confirmeCommande'),
    path('commande/filter', filter_commande, name='filter_commande'),
    path('commande/simulate', simulate_commande, name='simulate_commande'),
    path('commande/all', get_commande, name='get_commande'),
    path('commande/getall', get_all_commande, name='get_all_commande'),
    path('commande/getreserved', get_commande_reserved, name='get_commande_reserved'),
    path('commande/get/<int:idCommande>', get_commande_by_id, name='get_commande_by_id'),
    path('create', create, name='create'),
    path('upload', upload, name='upload'),
    path('search', search_room, name='search_room'),
    path('available', room_available, name='room_available'),
    path('unavailable', room_unavailable, name='room_unavailable'),
    path('createimage/<int:idRoom>', createimage, name='createimage'),
    path('imageall', imageall, name='imageall'),
    path('image/<int:idRoom>', image_room, name='image'),
    path('deleteimage/<int:idImage>', delete_image, name='delete_image'),
    path('get/<int:idRoom>', get_room, name='getRoom'),
    path('update/<int:idRoom>', update_by_admin, name='update'),
    path('free/<int:idRoom>', free_room, name='free_room'),
    path('delete/<int:idRoom>', delete_by_admin, name='delete'),
    path('recover/<int:idRoom>', recover_by_admin, name='recover'),
]