version: "3.9"

services:
  backend:
    build: .
    ports:
      - "10000:10000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:10000"
