# Generated by Django 4.1.13 on 2024-11-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hot_users', '0001_initial'),
        ('hot_clients', '0001_initial'),
        ('hot_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('idRoom', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('dateAvailable', models.DateTimeField(blank=True, null=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('idAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_users.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeRoom',
            fields=[
                ('idCommande', models.AutoField(primary_key=True, serialize=False)),
                ('DateStart', models.DateTimeField()),
                ('DateEnd', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('idAdmin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hot_users.user')),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_clients.client')),
                ('idRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_rooms.room')),
                ('idStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_services.status')),
            ],
        ),
    ]
