# Generated by Django 4.1.13 on 2024-12-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_rooms', '0002_alter_room_price_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanderoom',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commanderoom',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
