# Generated by Django 4.1.13 on 2025-01-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hot_services', '0004_itemimage'),
        ('hot_clients', '0001_initial'),
        ('hot_rooms', '0003_commanderoom_price_commanderoom_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanderoom',
            name='idClient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hot_clients.client'),
        ),
        migrations.AlterField(
            model_name='commanderoom',
            name='idRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hot_rooms.room'),
        ),
        migrations.AlterField(
            model_name='commanderoom',
            name='idStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hot_services.status'),
        ),
    ]
