# Generated by Django 4.1.13 on 2025-01-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_rooms', '0004_alter_commanderoom_idclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanderoom',
            name='payed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
