# Generated by Django 5.1.4 on 2025-01-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_rooms', '0005_commanderoom_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanderoom',
            name='DateStart',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='idRoom',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='subTitle',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
