# Generated by Django 5.1.4 on 2025-01-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_rooms', '0006_alter_commanderoom_datestart_alter_room_idroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanderoom',
            name='dateReceived',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commanderoom',
            name='received',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
