# Generated by Django 5.1.4 on 2025-01-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_rooms', '0007_commanderoom_datereceived_commanderoom_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanderoom',
            name='DateFreed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='commanderoom',
            name='refund',
            field=models.IntegerField(default=0),
        ),
    ]
