# Generated by Django 4.1.13 on 2024-11-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hot_users', '0001_initial'),
        ('hot_rooms', '0001_initial'),
        ('hot_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeHistorique',
            fields=[
                ('idType', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('idHistorique', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('idCommande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hot_rooms.commanderoom')),
                ('idCommandeService', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hot_services.commandeservice')),
                ('idType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_history.typehistorique')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_users.user')),
            ],
        ),
    ]
