# Generated by Django 4.1.13 on 2024-12-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hot_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historique',
            old_name='idUser',
            new_name='idAdmin',
        ),
        migrations.RenameField(
            model_name='historique',
            old_name='idCommande',
            new_name='idCommandeRoom',
        ),
    ]
