# Generated by Django 4.1.13 on 2025-01-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hot_users', '0003_user_image'),
        ('hot_rooms', '0003_commanderoom_price_commanderoom_total'),
        ('hot_history', '0002_rename_iduser_historique_idadmin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRoom',
            fields=[
                ('idHistory', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('idAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_users.user')),
                ('idRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_rooms.room')),
            ],
        ),
    ]
