# Generated by Django 4.1.13 on 2024-11-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idRole', models.AutoField(primary_key=True, serialize=False)),
                ('poste', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('genre', models.CharField(blank=True, max_length=10, null=True)),
                ('adress', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('idRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_users.role')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('idPreference', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_users.user')),
            ],
        ),
    ]
