# Generated by Django 4.1.13 on 2024-12-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordVersion',
            field=models.IntegerField(default=1),
        ),
    ]
