# Generated by Django 4.1.13 on 2024-12-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_users', '0002_user_passwordversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
