# Generated by Django 5.1.4 on 2025-01-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_users', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='idRole',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='poste',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='idUser',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
