# Generated by Django 5.1.1 on 2024-09-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address_client', models.TextField(blank=True, null=True)),
                ('position_lat', models.FloatField(blank=True, null=True)),
                ('position_long', models.FloatField(blank=True, null=True)),
                ('password_client', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('validation_client', models.BooleanField(default=False)),
                ('code', models.BigIntegerField(blank=True, null=True)),
                ('status_client', models.BooleanField(default=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
