# Generated by Django 5.1.1 on 2024-09-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('adminuser', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('start_date_reservation', models.DateField()),
                ('end_date_reservation', models.DateField()),
                ('payment', models.BooleanField(default=False)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activite')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminuser.useradmin')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.userclient')),
            ],
        ),
    ]
