# Generated by Django 5.1.4 on 2025-01-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_clients', '0002_alter_client_cin_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='idClient',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
