# Generated by Django 4.1.13 on 2024-11-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hot_users', '0001_initial'),
        ('hot_clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idService', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('idStatus', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('idItem', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('unity', models.CharField(blank=True, max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_services.service')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeService',
            fields=[
                ('idCommande', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('idAdmin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hot_users.user')),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_clients.client')),
                ('idItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_services.serviceitem')),
                ('idStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_services.status')),
            ],
        ),
    ]
