# Generated by Django 4.1.13 on 2024-12-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hot_users', '0002_user_passwordversion'),
        ('hot_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='idUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hot_users.user'),
        ),
    ]
