# Generated by Django 4.1.13 on 2024-12-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_services', '0002_serviceitem_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeservice',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
