# Generated by Django 4.1.13 on 2024-12-16 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hot_services', '0003_commandeservice_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('idImage', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('idItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hot_services.serviceitem')),
            ],
        ),
    ]
