# Generated by Django 5.1.4 on 2025-01-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_services', '0004_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='idService',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
