# Generated by Django 5.1.4 on 2025-01-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_services', '0006_commandeservice_datereceived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeservice',
            name='payed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
