# Generated by Django 5.1.1 on 2024-09-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminuser', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_activite', models.BooleanField(default=False)),
                ('reserved', models.BooleanField(default=False)),
                ('start_date_activite', models.DateField()),
                ('end_date_activite', models.DateField()),
                ('price', models.IntegerField()),
                ('photo', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminuser.useradmin')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.userclient')),
                ('type_activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.typeactivite')),
            ],
        ),
    ]
